# Form implementation generated from reading ui file 'login2.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        """
        Sets up the UI components for the login widget.

        Args:
            LoginWindow (QWidget): The QWidget instance to configure.
        """
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(700, 400)
        LoginWindow.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        LoginWindow.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)

        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")

        layout = QtWidgets.QVBoxLayout(self.centralwidget)

        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setStyleSheet(
            "QPushButton#pushButton{\n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
            "    color:rgba(255, 255, 255, 210);\n"
            "    border-radius: 5px;\n"
            "}\n"
            "QPushButton#pushButton:hover{\n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 188, 132, 226));\n"
            "}\n"
            "QPushButton#pushButton:pressed{\n"
            "    padding-left:5px;\n"
            "    padding-top:5px;\n"
            "    background-color:rgba(105, 118, 132, 200);\n"
            "}"
        )

        self.label_Background1 = QtWidgets.QLabel(parent=self.widget)
        self.label_Background1.setGeometry(QtCore.QRect(30, 20, 600, 290))
        self.label_Background1.setStyleSheet(
            "border-image: url(:/Images/flag.jpg);\n" "border-radius: 20px;"
        )
        self.label_Background1.setText("")
        self.label_Background1.setObjectName("label_Background1")

        self.label_Background2 = QtWidgets.QLabel(parent=self.widget)
        self.label_Background2.setGeometry(QtCore.QRect(30, 20, 600, 290))
        self.label_Background2.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop: 0.835227 rgba(0, 0, 0, 75));\n"
            "border-radius: 20px;"
        )
        self.label_Background2.setText("")
        self.label_Background2.setObjectName("label_Background2")

        self.label_Background3 = QtWidgets.QLabel(parent=self.widget)
        self.label_Background3.setGeometry(QtCore.QRect(40, 40, 570, 260))
        self.label_Background3.setStyleSheet(
            "background-color: rgba(0, 0, 0, 100);\n" "border-radius: 15px;"
        )
        self.label_Background3.setObjectName("label_Background3")

        self.label_Header = QtWidgets.QLabel(parent=self.widget)
        self.label_Header.setGeometry(QtCore.QRect(180, 40, 301, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_Header.setFont(font)
        self.label_Header.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.label_Header.setObjectName("label_Header")

        self.lineEdit_ID = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_ID.setGeometry(QtCore.QRect(220, 130, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_ID.setFont(font)
        self.lineEdit_ID.setStyleSheet(
            "background-color:rgba(0, 0, 0, 0);\n"
            "border:none;\n"
            "border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
            "color:rgba(255, 255, 255 230);\n"
            "padding-bottom: 7px"
        )
        self.lineEdit_ID.setObjectName("lineEdit_ID")

        self.lineEdit_Pin = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_Pin.setGeometry(QtCore.QRect(220, 190, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Pin.setFont(font)
        self.lineEdit_Pin.setStyleSheet(
            "background-color:rgba(0, 0, 0, 0);\n"
            "border:none;\n"
            "border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
            "color:rgba(255, 255, 255 230);\n"
            "padding-bottom: 7px"
        )
        self.lineEdit_Pin.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_Pin.setObjectName("lineEdit_Pin")

        self.pushButton_login = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_login.setGeometry(QtCore.QRect(220, 240, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setObjectName("pushButton_login")

        self.label_Err = QtWidgets.QLabel(parent=self.widget)
        self.label_Err.setGeometry(QtCore.QRect(220, 90, 211, 31))
        self.label_Err.setStyleSheet(
            "background-color: rgb(255, 193, 174);\n"
            "border: 1px solid;\n"
            "border-color:rgb(255, 0, 0);"
        )
        self.label_Err.setText("")
        self.label_Err.setObjectName("label_Err")
        self.label_Err.setVisible(False)

        layout.addWidget(self.widget)

        self.centralwidget.setLayout(layout)

        LoginWindow.setLayout(layout)

        self.label_Background1.setGraphicsEffect(
            QtWidgets.QGraphicsDropShadowEffect(
                blurRadius=25,
                xOffset=0,
                yOffset=0,
                color=QtGui.QColor(234, 221, 186, 100),
            )
        )

        self.label_Background3.setGraphicsEffect(
            QtWidgets.QGraphicsDropShadowEffect(
                blurRadius=25,
                xOffset=0,
                yOffset=0,
                color=QtGui.QColor(105, 118, 132, 100),
            )
        )

        self.pushButton_Login.setGraphicsEffect(
            QtWidgets.QGraphicsDropShadowEffect(
                blurRadius=25,
                xOffset=3,
                yOffset=3,
                color=QtGui.QColor(105, 118, 132, 100),
            )
        )

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label_Background3.setText(_translate("LoginWindow", "TextLabel"))
        self.label_Header.setText(_translate("LoginWindow", "Federal Ballot Service"))
        self.lineEdit_ID.setPlaceholderText(_translate("LoginWindow", "Voter ID"))
        self.lineEdit_Pin.setPlaceholderText(_translate("LoginWindow", "PIN"))
        self.pushButton_login.setText(_translate("LoginWindow", "L o g i n"))
